[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "inotia00 ReVanced"
arch = "arm64-v8a"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "inotia00 ReVanced"
arch = "arm64-v8a"

[Tiktok]
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
arch = "arm64-v8a"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
arch = "arm64-v8a"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "inotia00 ReVanced"
arch = "arm64-v8a"

[Bandcamp]
apkmirror-dlurl = "https://www.apkmirror.com/apk/bandcamp-inc/bandcamp/"
arch = "arm64-v8a"

[Photos]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
arch = "arm64-v8a"

[Lightroom]
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"
arch = "arm64-v8a"

[Sync]
apkmirror-dlurl = "https://www.apkmirror.com/apk/sync-apps-ltd/sync-for-lemmy/"
arch = "arm64-v8a"

[SoundCloud]
apkmirror-dlurl = "https://www.apkmirror.com/apk/soundcloud/soundcloud-soundcloud/"
arch = "arm64-v8a"

[Spotify]
apkmirror-dlurl = "https://www.apkmirror.com/apk/spotify-ab/spotify-music-podcasts/"
arch = "arm64-v8a"

[Tumblr]
apkmirror-dlurl = "https://www.apkmirror.com/apk/tumblr-inc/tumblr/"
arch = "arm64-v8a"
